services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL=postgres://user:pass@test-db:5432/jimu_test?sslmode=disable
    depends_on:
      - test-db

  test-db:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: jimu_test